version: '3.9'

services:

  postgres-db-student:
    image: postgres
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres-datadir:/var/lib/postgresql/data-student
    deploy:
      replicas: 1

volumes:
  postgres-datadir: #